### ISSUE TITLE
 The payload is invalid

### ISSUE THREAD

**Issue by nemo3000** [rahulhaque/laravel-filepond#27]
I did a basic configuration of filepond.
**Client side:**
```
FilePond.setOptions({
        credits: false,
        allowMultiple: true,
        server: {
            url: 'url',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
            }
        }
    });

FilePond.create(document.querySelector('input[name="nuovo_file"]'));
```

**Server side:**
`$fileInfo = Filepond::field('nuovo_file')->getFile();`

I have this error:
 The payload is invalid. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:214

if I use this code on server side work fine:
```
$file=$request->file('nuovo_file');
$nomeFile=$file->getClientOriginalName();
........

```
Can some one help me?

**Comment by rahulhaque** [comment]
@nemo3000 follow the example first as it is to understand the basics of filepond. It seems to me your filepond config is incorrect. What is the actual 'url' in the `Filepond.setOptions()`. It should point to your backend. `$request->file('nuovo_file')` will not work if you're successfully using filepond.

**Comment by nemo3000** [comment]
Sorry I'm afraid I was unclear. 'url' points to my backend with the correct address, I replaced the address in the post. If, on the other hand, I read the file directly from the request, I can normally do all the operations, as in my example with $file = $request-> file ('nuovo_file').
In my form the name of the file field is 'nuovo_file'

**Comment by rahulhaque** [comment]
@nemo3000 the thing is, you should not be able to read the file directly while using filepond correctly. Filepond itself uploads the file to backend when a file is selected. Did you see filepond turning green when a file is choosen? When you submit the form, what is the output of `dd($request->all())`?

**Comment by nemo3000** [comment]
I see upload counter but aftern tun red with error 500 for payload is invalid.
My dd result is:
```
^ array:2 [
  "nuovo_file" => Illuminate\Http\UploadedFile {#483
    -test: false
    -originalName: "A LA CARTE MENU Marzo 2022.pdf"
    -mimeType: "application/pdf"
    -error: 0
    #hashName: null
    path: "/tmp"
    filename: "php7PfT7H"
    basename: "php7PfT7H"
    pathname: "/tmp/php7PfT7H"
    extension: ""
    realPath: "/tmp/php7PfT7H"
    aTime: 2022-09-22 12:28:34
    mTime: 2022-09-22 12:28:34
    cTime: 2022-09-22 12:28:34
    inode: 1051150
    size: 68337
    perms: 0100600
    owner: 33
    group: 33
    type: "file"
    writable: true
    readable: true
    executable: false
    file: true
    dir: false
    link: false
  }
  "richieste_id" => "241"
]
```

**Comment by rahulhaque** [comment]
@nemo3000 what do you see in network request (in browser's console) when you drop the file in filepond area?

**Comment by nemo3000** [comment]
I have already disabled allowMultiple:true but is the same.

This is a block of  payload request:
![immagine](https://user-images.githubusercontent.com/5304942/191730859-61f4c61c-98cf-4058-91df-92b5eeb6c260.png)

**Comment by rahulhaque** [comment]
@nemo3000 I asked for the response of network call made by filepond library, not payload from browser.

**Comment by nemo3000** [comment]
Do you mean this?
```
[2022-09-22 15:52:09] local.ERROR: The payload is invalid. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:214)
[stacktrace]
#0 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(151): Illuminate\\Encryption\\Encrypter->getJsonPayload()
#1 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\\Encryption\\Encrypter->decrypt()
#2 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/AbstractFilepond.php(152): Illuminate\\Support\\Facades\\Facade::__callStatic()
#3 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/AbstractFilepond.php(56): RahulHaque\\Filepond\\AbstractFilepond->decrypt()
#4 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/Filepond.php(19): RahulHaque\\Filepond\\AbstractFilepond->setFieldValue()
#5 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): RahulHaque\\Filepond\\Filepond->field()
#6 /var/www/zetagest/app/Http/Controllers/Assistenze/CRichieste.php(280): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Assistenze\\CRichieste::file_process()
#8 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\Route->runController()
#11 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#12 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/zetagest/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle()
#15 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#47 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/zetagest/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"} 
```

**Comment by nemo3000** [comment]
Yes exactly.
I use only input field.
```
<div id="divCardAllegati">
          <input type="file" class="my-pond-richieste" name="nuovo_file"/>
</div>
```

**Comment by rahulhaque** [comment]
@nemo3000 and how does this input field looks like in the browser?

**Comment by nemo3000** [comment]
I suppose how normal it is

![immagine](https://user-images.githubusercontent.com/5304942/191836959-e9b0641a-9e48-47d5-b7f0-247db5d6bf6e.png)

**Comment by rahulhaque** [comment]
@nemo3000 ok, your filepond loaded alright. Now open dev tools network tab in the browser. When you drop a file on it, it should make a network request to upload the file. What response you're getting from that request?

**Comment by nemo3000** [comment]
simple 500

**Comment by rahulhaque** [comment]
@nemo3000 that means filepond not finding path to upload dropped files. Either your package configuration has issues or server url for filepond is wrong. Check the package documentation if you've missed anything. I can't help you without seeing your code or you pinpointing the error.

**Comment by rahulhaque** [comment]
Closing due to inactivity.

**Comment by bravonet** [comment]
hi @rahulhaque i manage to reproduce the following error by enabling the laravel debugger. as long as the debugger bar is appearing the upload will eventually return 500 with the following error.

```
[2022-09-22 15:52:09] local.ERROR: The payload is invalid. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:214)
[stacktrace]
#0 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(151): Illuminate\\Encryption\\Encrypter->getJsonPayload()
#1 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\\Encryption\\Encrypter->decrypt()
#2 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/AbstractFilepond.php(152): Illuminate\\Support\\Facades\\Facade::__callStatic()
#3 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/AbstractFilepond.php(56): RahulHaque\\Filepond\\AbstractFilepond->decrypt()
#4 /var/www/zetagest/vendor/rahulhaque/laravel-filepond/src/Filepond.php(19): RahulHaque\\Filepond\\AbstractFilepond->setFieldValue()
#5 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): RahulHaque\\Filepond\\Filepond->field()
#6 /var/www/zetagest/app/Http/Controllers/Assistenze/CRichieste.php(280): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Assistenze\\CRichieste::file_process()
#8 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\Route->runController()
#11 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#12 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/zetagest/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle()
#15 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#47 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/zetagest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/zetagest/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"} 
```

**Comment by rahulhaque** [comment]
@nemo3000 the issue with laravel debugbar is fully explained in the documentation. It was there from the beginning.
